language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update && sudo apt-get install -y fglrx opencl-headers lcov doxygen;
script:
  - cd tests
  - make
  - "./gpu-list"
  - "./cpu-list"
branches:
  only:
    - master
notifications:
  email: false
os:
  - linux
